# Generated by Django 2.0.2 on 2018-02-26 22:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_triggered', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('alert_text', models.TextField()),
                ('alert_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('actions', models.ManyToManyField(to='vigil.AlertAction')),
            ],
        ),
    ]
