# Generated by Django 2.0.2 on 2018-02-26 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='alertaction',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vigil.ActionTask'),
            preserve_default=False,
        ),
    ]
