# Generated by Django 2.0.2 on 2018-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0003_auto_20180226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='actions',
            field=models.ManyToManyField(blank=True, null=True, to='vigil.AlertAction'),
        ),
    ]
