# Generated by Django 2.0.2 on 2018-02-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0005_auto_20180226_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaction',
            name='task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.ActionTask'),
        ),
    ]
