# Generated by Django 2.0.2 on 2018-02-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0007_auto_20180226_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontask',
            name='name',
        ),
    ]
