# Generated by Django 2.0.2 on 2018-02-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0008_remove_actiontask_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiontask',
            old_name='task',
            new_name='name',
        ),
    ]
