# Generated by Django 2.0.2 on 2018-02-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0009_auto_20180227_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertaction',
            old_name='action_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='alertchannel',
            old_name='alert_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='alertchannel',
            old_name='alert_text',
            new_name='text',
        ),
    ]
