# Generated by Django 2.0.2 on 2018-02-27 00:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0010_auto_20180227_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaction',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
