# Generated by Django 2.0.2 on 2018-02-28 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0013_auto_20180227_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertchannel',
            old_name='text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='data',
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='alert_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
