# Generated by Django 2.0.2 on 2018-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0014_auto_20180228_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Urgent', 'URGENT'), ('Emergency', 'EMERGENCY')], max_length=255, null=True),
        ),
    ]
