# Generated by Django 2.0.2 on 2018-03-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0015_auto_20180228_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='set_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
