# Generated by Django 2.0.2 on 2018-03-12 12:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0016_alertchannel_set_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='repeat_time',
            field=models.DurationField(default=datetime.timedelta(0, 300), help_text='Alert Actions will only be triggered this frequently, even if the alert details change'),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='time_to_urgent',
            field=models.DurationField(default=datetime.timedelta(0, 900), help_text='After this period, the Alert Channel Priority will be upgraded to URGENT'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='What actions to attach to this Alert Channel', to='vigil.AlertAction'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='alert_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='message',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='name',
            field=models.CharField(help_text='The name for this Alert Channel', max_length=255),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Urgent', 'URGENT'), ('Emergency', 'EMERGENCY')], editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='set_active',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
