# Generated by Django 2.0.3 on 2018-03-13 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0017_auto_20180312_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='actions',
            field=models.ManyToManyField(blank=True, help_text='Which Alert Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', to='vigil.AlertAction'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='repeat_time',
            field=models.DurationField(default=datetime.timedelta(0, 900), help_text='Alert Actions will only be triggered this frequently, even if the alert details change'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='time_to_urgent',
            field=models.DurationField(default=datetime.timedelta(0, 3600), help_text='After this period, the Alert Channel Priority will be upgraded to URGENT'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
