# Generated by Django 2.0.3 on 2018-03-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0018_auto_20180313_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=500, null=True)),
                ('message', models.TextField(blank=True, editable=False, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Urgent', 'URGENT'), ('Emergency', 'EMERGENCY')], editable=False, max_length=255, null=True)),
                ('alert_created', models.DateTimeField(auto_now_add=True)),
                ('alert_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertChannel')),
            ],
        ),
    ]
