# Generated by Django 2.0.3 on 2018-03-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0020_historicalalert_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertchannel',
            name='last_updated',
        ),
    ]
