# Generated by Django 2.0.3 on 2018-03-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0021_remove_alertchannel_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='action_type',
            field=models.CharField(choices=[('Notification', 'NOTIFICATION'), ('Logic', 'LOGIC')], default='Notification', max_length=20),
            preserve_default=False,
        ),
    ]
