# Generated by Django 2.0.3 on 2018-03-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('vigil', '0022_actiontask_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigilTaskResult',
            fields=[
                ('taskresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_results.TaskResult')),
                ('alert_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertAction')),
            ],
            bases=('django_celery_results.taskresult',),
        ),
        migrations.AlterModelOptions(
            name='historicalalert',
            options={'ordering': ['-alert_created']},
        ),
    ]
