# Generated by Django 2.0.3 on 2018-03-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0023_auto_20180314_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigiltaskresult',
            name='alert_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertChannel'),
        ),
    ]
