# Generated by Django 2.0.3 on 2018-03-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0024_vigiltaskresult_alert_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('alert_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertAction')),
                ('alert_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertChannel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='vigiltaskresult',
            options={'ordering': ['-date_done']},
        ),
        migrations.AddField(
            model_name='actiontask',
            name='sub_tasks',
            field=models.ManyToManyField(to='vigil.ActionTask'),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='alert_actions',
            field=models.ManyToManyField(blank=True, help_text='Which Alert Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='alert_actions', through='vigil.ChannelAction', to='vigil.AlertAction'),
        ),
    ]
