# Generated by Django 2.0.3 on 2018-03-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0025_auto_20180314_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelaction',
            options={'ordering': ['priority']},
        ),
        migrations.RenameField(
            model_name='alertchannel',
            old_name='actions',
            new_name='simple_actions',
        ),
        migrations.AlterField(
            model_name='channelaction',
            name='alert_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='vigil.AlertAction'),
        ),
        migrations.AlterField(
            model_name='channelaction',
            name='alert_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='vigil.AlertChannel'),
        ),
    ]
