# Generated by Django 2.0.3 on 2018-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0026_auto_20180314_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelaction',
            options={'ordering': ['alert_channel', 'priority']},
        ),
        migrations.RemoveField(
            model_name='actiontask',
            name='sub_tasks',
        ),
    ]
