# Generated by Django 2.0.3 on 2018-03-16 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0027_auto_20180315_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertchannel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='actiontask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='action_type',
            field=models.CharField(choices=[('PreProcessor', 'PREPROCESSOR'), ('Notification', 'NOTIFICATION'), ('Logic', 'LOGIC')], help_text='Action types are handled in different ways. "Preprocessor" type tasks run sequentially based on the "priority". "Notification" and "Logic" type tasks are run as a groupso all execute in parallel', max_length=20),
        ),
        migrations.AlterField(
            model_name='actiontask',
            name='default_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='This is a representation of the data that the Action Task expects to be passed to it when it is called. This automatically populates the AlertAction.data attribute when a task is associated with an AlertAction'),
        ),
    ]
