# Generated by Django 2.0.3 on 2018-03-16 14:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vigil', '0028_auto_20180316_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelLogicAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['alert_channel', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='LogicActionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party')),
                ('business_logic_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data required from AlertAction to allow the business logic to function.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogicAlertAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.LogicActionTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationActionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data required for the notification task to function. Normally API details or similar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationAlertAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.NotificationActionTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreProcessorActionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party')),
                ('priority_levels', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The levels to apply to calculate the priority of the alert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='alertaction',
            name='task',
        ),
        migrations.RemoveField(
            model_name='channelaction',
            name='alert_action',
        ),
        migrations.RemoveField(
            model_name='channelaction',
            name='alert_channel',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='alert_actions',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='simple_actions',
        ),
        migrations.RemoveField(
            model_name='vigiltaskresult',
            name='alert_action',
        ),
        migrations.AddField(
            model_name='vigiltaskresult',
            name='alert_task_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vigiltaskresult',
            name='alert_task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.DeleteModel(
            name='ActionTask',
        ),
        migrations.DeleteModel(
            name='AlertAction',
        ),
        migrations.DeleteModel(
            name='ChannelAction',
        ),
        migrations.AddField(
            model_name='channellogicaction',
            name='alert_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='vigil.AlertChannel'),
        ),
        migrations.AddField(
            model_name='channellogicaction',
            name='logic_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='vigil.LogicAlertAction'),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='logic_actions',
            field=models.ManyToManyField(blank=True, help_text='Which Alert Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='logic_actions', through='vigil.ChannelLogicAction', to='vigil.LogicAlertAction'),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='notification_actions',
            field=models.ManyToManyField(blank=True, help_text='Which Alert Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='notification_actions', to='vigil.NotificationAlertAction'),
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='preprocessor_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.PreProcessorActionTask'),
        ),
    ]
