# Generated by Django 2.0.3 on 2018-03-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0030_preprocessoralertaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='preprocessor_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.PreProcessorAlertAction'),
        ),
    ]
