# Generated by Django 2.0.3 on 2018-03-16 16:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0031_auto_20180316_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logicalertaction',
            name='data',
        ),
        migrations.RemoveField(
            model_name='preprocessoralertaction',
            name='data',
        ),
        migrations.AddField(
            model_name='logicalertaction',
            name='business_logic_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data required from AlertAction to allow the business logic to function.'),
        ),
        migrations.AddField(
            model_name='logicalertaction',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party'),
        ),
        migrations.AddField(
            model_name='preprocessoralertaction',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party'),
        ),
        migrations.AddField(
            model_name='preprocessoralertaction',
            name='priority_levels',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The levels to apply to calculate the priority of the alert'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='preprocessor_action',
            field=models.ForeignKey(blank=True, help_text='does this work? {% url "preprocessor_alert_action-create" %}', null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.PreProcessorAlertAction'),
        ),
        migrations.AlterField(
            model_name='logicactiontask',
            name='business_logic_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logicactiontask',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preprocessoractiontask',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preprocessoractiontask',
            name='priority_levels',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
