# Generated by Django 2.0.3 on 2018-03-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0033_alertchannel_new_logic_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertchannel',
            name='logic_actions',
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='old_logic_actions',
            field=models.ManyToManyField(blank=True, help_text='Which Alert Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='old_logic_actions', through='vigil.ChannelLogicAction', to='vigil.LogicAlertAction'),
        ),
    ]
