# Generated by Django 2.0.3 on 2018-03-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0035_auto_20180316_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertchannel',
            name='old_logic_actions',
        ),
    ]
