# Generated by Django 2.0.3 on 2018-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0036_remove_alertchannel_old_logic_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channellogicaction',
            name='alert_channel',
        ),
        migrations.RemoveField(
            model_name='channellogicaction',
            name='logic_action',
        ),
        migrations.AddField(
            model_name='logicalertaction',
            name='notification_actions',
            field=models.ManyToManyField(blank=True, null=True, to='vigil.NotificationAlertAction'),
        ),
        migrations.DeleteModel(
            name='ChannelLogicAction',
        ),
    ]
