# Generated by Django 2.0.3 on 2018-03-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0037_auto_20180316_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logicalertaction',
            name='notification_actions',
            field=models.ManyToManyField(blank=True, to='vigil.NotificationAlertAction'),
        ),
    ]
