# Generated by Django 2.0.3 on 2018-03-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0038_auto_20180316_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='auto_acknowledge',
            field=models.DateTimeField(blank=True, help_text='If set, alert channels will ato acknowledge if they are not updated after this amount of time', null=True),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='preprocessor_action',
            field=models.ForeignKey(blank=True, help_text='This action will be used to pre-process incoming alert data to format a title, message and priority for the alert', null=True, on_delete=django.db.models.deletion.CASCADE, to='vigil.PreProcessorAlertAction'),
        ),
    ]
