# Generated by Django 2.0.3 on 2018-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0039_auto_20180317_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='logic_actions',
            field=models.ManyToManyField(blank=True, help_text='Logic Actions process the incoming alert data \n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='logic_actions', to='vigil.LogicAlertAction'),
        ),
    ]
