# Generated by Django 2.0.3 on 2018-05-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0040_auto_20180503_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessoralertaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_task', related_query_name='action_tasks', to='vigil.PreProcessorActionTask'),
        ),
    ]
