# Generated by Django 2.0.3 on 2018-05-03 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0042_auto_20180503_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The cumulative expected data of the preprocessor, and all logic, alert actions'),
        ),
    ]
