# Generated by Django 2.0.3 on 2018-05-04 08:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0043_alertchannel_expected_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=500, null=True)),
                ('message', models.TextField(blank=True, editable=False, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Urgent', 'URGENT'), ('Emergency', 'EMERGENCY')], editable=False, max_length=255, null=True)),
                ('active', models.BooleanField(default=False, editable=False)),
                ('alert_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'ordering': ['-alert_created'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalalert',
            name='alert_channel',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='active',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='set_active',
        ),
        migrations.RemoveField(
            model_name='alertchannel',
            name='title',
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='auto_acknowledge',
            field=models.DateTimeField(blank=True, help_text='If set, alert channels will auto acknowledge if they are not updated after this amount of time', null=True),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='expected_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='When activated through the API, this Alert Channel expects these attributes in the POST data'),
        ),
        migrations.DeleteModel(
            name='HistoricalAlert',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vigil.AlertChannel'),
        ),
    ]
