# Generated by Django 2.0.3 on 2018-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0044_auto_20180504_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='updated',
        ),
        migrations.AddField(
            model_name='alert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
