# Generated by Django 2.0.3 on 2018-05-04 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0045_auto_20180504_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RenameField(
            model_name='alertchannel',
            old_name='time_to_urgent',
            new_name='time_to_upgrade',
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='notification_actions',
            field=models.ManyToManyField(blank=True, help_text='Notification Actions are attached to this Alert Channel\n(highlighted entries are added. Ctrl+select to choose multiple)', related_name='notification_actions', to='vigil.NotificationAlertAction'),
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='repeat_time',
            field=models.DurationField(default=datetime.timedelta(0, 900), help_text='Notification Alert Actions will only be triggered this frequently, even if the alert details change'),
        ),
    ]
