# Generated by Django 2.0.3 on 2018-05-04 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0046_auto_20180504_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertchannel',
            name='acknowledge',
            field=models.DurationField(default=datetime.timedelta(0, 10800), help_text='If set, alert channels will auto acknowledge if they are not updated after this amount of time'),
        ),
    ]
