# Generated by Django 2.0.3 on 2018-05-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0047_alertchannel_acknowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertchannel',
            name='auto_acknowledge',
        ),
    ]
