# Generated by Django 2.0.3 on 2018-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0049_auto_20180504_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessoractiontask',
            name='priority_levels',
        ),
        migrations.RemoveField(
            model_name='preprocessoralertaction',
            name='priority_levels',
        ),
        migrations.AddField(
            model_name='alertchannel',
            name='base_priority',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Urgent', 'URGENT'), ('Emergency', 'EMERGENCY')], default='Low', max_length=255),
        ),
    ]
