# Generated by Django 2.0.3 on 2018-05-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0051_auto_20180504_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationalertaction',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
