# Generated by Django 2.0.3 on 2018-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0052_notificationalertaction_last_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
