# Generated by Django 2.0.3 on 2018-05-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0053_alert_last_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_priority_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
