# Generated by Django 3.1.1 on 2020-09-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigil', '0054_alert_last_priority_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='expected_data',
            field=models.JSONField(blank=True, default=dict, help_text='When activated through the API, this Alert Channel expects these attributes in the POST data'),
        ),
        migrations.AlterField(
            model_name='logicactiontask',
            name='business_logic_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logicactiontask',
            name='expected_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logicalertaction',
            name='business_logic_data',
            field=models.JSONField(blank=True, default=dict, help_text='The data required from AlertAction to allow the business logic to function.'),
        ),
        migrations.AlterField(
            model_name='logicalertaction',
            name='expected_data',
            field=models.JSONField(blank=True, default=dict, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party'),
        ),
        migrations.AlterField(
            model_name='notificationactiontask',
            name='default_data',
            field=models.JSONField(blank=True, default=dict, help_text='The data required for the notification task to function. Normally API details or similar'),
        ),
        migrations.AlterField(
            model_name='notificationalertaction',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preprocessoractiontask',
            name='expected_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='preprocessoralertaction',
            name='expected_data',
            field=models.JSONField(blank=True, default=dict, help_text='The data that is expected from the 3rd party system. This forms the basis of a data contract with the 3rd party'),
        ),
    ]
